# -*- coding: utf-8 -*-
"""Baekjoon

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13TyTHLk_5MACqRcWrWok66lVDD4HXUfQ
"""

#2884
h,m=map(int,input().split())

if m>=45:
  m-=45
elif h!=0 and m<45:
  h-=1
  m+=15
else:
  h=23
  m+=15
print(h,end=' ')
print(m)