# -*- coding: utf-8 -*-
"""Baekjoon

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13TyTHLk_5MACqRcWrWok66lVDD4HXUfQ
"""

#2525
h,m=map(int,input().split())
t=int(input())

if m+t<60:
  print(h,m+t)
else:
  extra_hour=(m+t)//60
  if h+extra_hour<24:
    print(h+extra_hour,(m+t)%60)
  else:
    print((h+extra_hour)%24,(m+t)%60)