# -*- coding: utf-8 -*-
"""Baekjoon

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13TyTHLk_5MACqRcWrWok66lVDD4HXUfQ
"""

#14681
x=int(input())
y=int(input())

if x>0 and y>0:
  print('1')
elif x>0 and y<0:
  print('4')
elif x<0 and y>0:
  print('2')
else:
  print('3')